name: Run tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: 2.9.3

      - name: Check types
        run: deno check **/*.{ts,mts}

      - name: Check format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Run tests
        run: deno test
